# Generated by Django 5.1.15 on 2026-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions_override',
            field=models.JSONField(blank=True, default=dict, help_text='Per-user permission overrides set by the Super Admin. Keys are entries in User.PERMISSION_KEYS, values are True/False. Omitted keys fall back to the role-derived default.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('director', 'Director'), ('chief_registrar', 'Chief Registrar'), ('president', 'President')], default='admin_staff', max_length=20),
        ),
    ]
