# Generated by Django 5.1.15 on 2026-05-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('*', 'All roles'), ('admin_staff', 'Admin Staff'), ('director', 'Director'), ('chief_registrar', 'Chief Registrar'), ('president', 'President')], db_index=True, default='*', max_length=20)),
                ('type', models.CharField(choices=[('promotion_due', 'Promotion due'), ('retirement_soon', 'Retirement soon'), ('record_updated', 'Record updated')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_notifications', to='staff.staff')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_role', 'is_read', '-created_at'], name='notificatio_recipie_2a9148_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx')],
            },
        ),
    ]
