# Generated by Django 5.1.15 on 2026-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(choices=[('*', 'All roles'), ('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('director', 'Director'), ('chief_registrar', 'Chief Registrar'), ('president', 'President')], db_index=True, default='*', max_length=20),
        ),
    ]
