# Generated by Django 5.1.15 on 2026-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Legal, HR, Finance)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description and responsibilities', null=True)),
                ('department_code', models.CharField(help_text='Short code for the department (e.g., LEG, HR)', max_length=10, unique=True)),
                ('head_of_department', models.CharField(blank=True, help_text='Name of the department head', max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Department contact email', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Department phone number', max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Physical office location', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this department currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments_department',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='departments_name_33d25b_idx'), models.Index(fields=['department_code'], name='departments_departm_41bf7c_idx'), models.Index(fields=['is_active'], name='departments_is_acti_51d68f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title or designation', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the designation', null=True)),
                ('rank_order', models.IntegerField(help_text='Hierarchical rank (1=highest, for sorting)')),
                ('designation_type', models.CharField(choices=[('executive', 'Executive'), ('managerial', 'Managerial'), ('professional', 'Professional'), ('administrative', 'Administrative'), ('support', 'Support')], default='professional', help_text='Category of designation', max_length=50)),
                ('min_experience_required', models.IntegerField(default=0, help_text='Minimum years of experience required')),
                ('educational_requirement', models.TextField(blank=True, help_text='Educational qualifications required', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this designation currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'db_table': 'departments_designation',
                'ordering': ['rank_order', 'title'],
                'indexes': [models.Index(fields=['title'], name='departments_title_386ae5_idx'), models.Index(fields=['rank_order'], name='departments_rank_or_e7b524_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(help_text='Grade level code (e.g., GL10, GL12, GL14)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the grade level', null=True)),
                ('step_1_amount', models.DecimalField(decimal_places=2, help_text='Salary amount for step 1', max_digits=12)),
                ('number_of_steps', models.IntegerField(default=15, help_text='Number of steps in this grade (typically 15)')),
                ('increment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Annual increment amount per step', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Is this grade level currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'db_table': 'departments_gradelevel',
                'ordering': ['grade_level'],
                'indexes': [models.Index(fields=['grade_level'], name='departments_grade_l_cb2204_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the posting location', max_length=200, unique=True)),
                ('address', models.TextField(help_text='Full address of the location')),
                ('state', models.CharField(help_text='State where location is situated', max_length=50)),
                ('city', models.CharField(help_text='City or town', max_length=100)),
                ('location_code', models.CharField(help_text='Short code for the location', max_length=10, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person at the location', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, help_text='Details about the posting location', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this location currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posting Location',
                'verbose_name_plural': 'Posting Locations',
                'db_table': 'departments_postinglocation',
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['name'], name='departments_name_132614_idx'), models.Index(fields=['state'], name='departments_state_bda28b_idx'), models.Index(fields=['location_code'], name='departments_locatio_6f24e4_idx')],
            },
        ),
    ]
