# Generated by Django 5.1.15 on 2026-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinglocation',
            name='is_headquarters',
            field=models.BooleanField(default=False, help_text='Is this the headquarters duty station? Staff posted here are floated to the top of the nominal roll / staff list.'),
        ),
    ]
