# Generated by Django 5.1.15 on 2026-05-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Unique staff identification number', max_length=20, unique=True)),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name(s)', max_length=100, null=True)),
                ('last_name', models.CharField(help_text='Last name/Surname', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender', max_length=1)),
                ('nationality', models.CharField(default='Nigerian', help_text='Nationality', max_length=100)),
                ('state_of_origin', models.CharField(help_text='State of origin in Nigeria', max_length=100)),
                ('local_government_area', models.CharField(blank=True, help_text='Local Government Area (LGA)', max_length=150, null=True)),
                ('email', models.EmailField(help_text='Official email address', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Primary phone number', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=20, null=True)),
                ('residential_address', models.TextField(help_text='Current residential address')),
                ('residential_state', models.CharField(help_text='State of residence', max_length=100)),
                ('residential_city', models.CharField(help_text='City of residence', max_length=100)),
                ('passport_photo', models.ImageField(help_text='Passport-size photograph', upload_to='passport_photos/%Y/%m/')),
                ('passport_number', models.CharField(blank=True, help_text='International passport number', max_length=50, null=True)),
                ('national_identification', models.CharField(blank=True, help_text='National ID number', max_length=50, null=True)),
                ('nin', models.CharField(blank=True, help_text='National Identification Number', max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=50)),
                ('number_of_dependents', models.IntegerField(default=0, help_text='Number of dependents')),
                ('grade_step', models.IntegerField(default=1, help_text='Current step within grade level')),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Casual', 'Casual')], default='Permanent', help_text='Type of employment', max_length=50)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Retired', 'Retired'), ('Terminated', 'Terminated')], default='Active', help_text='Current employment status', max_length=50)),
                ('first_appointment_date', models.DateField(help_text='Date of first appointment to the organization')),
                ('last_promotion_date', models.DateField(blank=True, help_text='Date of last promotion', null=True)),
                ('next_promotion_date', models.DateField(blank=True, help_text='Auto-calculated next promotion date (3 years from last promotion)', null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Contract start date (if applicable)', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='Contract end date (if applicable)', null=True)),
                ('years_of_service', models.IntegerField(default=0, help_text='Total years of service (auto-calculated)')),
                ('retirement_date', models.DateField(blank=True, help_text='Calculated retirement date (age 60 or 35 years of service, whichever is earlier)', null=True)),
                ('retirement_date_age_60', models.DateField(blank=True, help_text='Date staff reaches age 60 (DOB + 60 years)', null=True)),
                ('retirement_date_service_35', models.DateField(blank=True, help_text='Date staff completes 35 years of service (first appointment + 35 years)', null=True)),
                ('retirement_basis', models.CharField(blank=True, choices=[('age', 'Age 60'), ('service', '35 years of service')], help_text='Which rule produced the earlier retirement date', max_length=10, null=True)),
                ('years_remaining_to_retirement', models.IntegerField(default=0, help_text='Whole years remaining until retirement (snapshot, refreshed on save)')),
                ('months_remaining_to_retirement', models.IntegerField(default=0, help_text='Total whole months remaining until retirement (snapshot, refreshed on save)')),
                ('highest_qualification', models.CharField(blank=True, help_text='Highest educational qualification', max_length=200, null=True)),
                ('professional_certifications', models.TextField(blank=True, help_text='Professional certifications and licenses', null=True)),
                ('next_of_kin_name', models.CharField(blank=True, help_text='Name of next of kin', max_length=200, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, help_text='Relationship to staff member', max_length=50, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, help_text='Phone number of next of kin', max_length=20, null=True)),
                ('next_of_kin_address', models.TextField(blank=True, help_text='Address of next of kin', null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person', max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of bank', max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('account_holder_name', models.CharField(blank=True, help_text='Account holder name', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the staff member active')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this record', max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=200, null=True)),
                ('department', models.ForeignKey(help_text='Current department', on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('designation', models.ForeignKey(help_text='Current designation/rank', on_delete=django.db.models.deletion.PROTECT, to='departments.designation')),
                ('grade_level', models.ForeignKey(blank=True, help_text='Current salary grade level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.gradelevel')),
                ('posting_location', models.ForeignKey(blank=True, help_text='Current posting location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.postinglocation')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'staff_staff',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('can_view_all_staff', 'Can view all staff records'), ('can_export_staff_records', 'Can export staff records'), ('can_approve_promotions', 'Can approve promotions'), ('can_manage_staff_documents', 'Can manage staff documents')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROMOTION_DUE', 'Promotion due'), ('PROMOTION_OVERDUE', 'Promotion overdue'), ('RETIREMENT_DUE', 'Retirement approaching'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('related_date', models.DateField(blank=True, help_text='The date this notification refers to (e.g. promotion due date).', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(help_text='Date of promotion')),
                ('previous_designation', models.CharField(help_text='Previous designation', max_length=150)),
                ('previous_grade', models.CharField(blank=True, help_text='Previous grade level', max_length=10, null=True)),
                ('new_grade_step', models.IntegerField(default=1, help_text='Step in new grade')),
                ('promotion_letter_ref', models.CharField(blank=True, help_text='Reference number of promotion letter', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks about the promotion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_designation', models.ForeignKey(help_text='New designation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.designation')),
                ('new_grade', models.ForeignKey(blank=True, help_text='New grade level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.gradelevel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Promotion',
                'verbose_name_plural': 'Staff Promotions',
                'db_table': 'staff_staffpromotion',
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(help_text='Effective date of the transfer.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the transfer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Username of user who recorded this transfer.', max_length=200, null=True)),
                ('from_location', models.ForeignKey(blank=True, help_text='Previous posting location (NULL for first posting).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='departments.postinglocation')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='staff.staff')),
                ('to_location', models.ForeignKey(help_text='New posting location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='departments.postinglocation')),
            ],
            options={
                'verbose_name': 'Staff Transfer',
                'verbose_name_plural': 'Staff Transfers',
                'db_table': 'staff_stafftransfer',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='staff_staff_staff_i_1228db_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='staff_staff_email_87de38_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department'], name='staff_staff_departm_5ebced_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['designation'], name='staff_staff_designa_cdd672_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='staff_staff_is_acti_0db61a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['first_name', 'last_name'], name='staff_staff_first_n_f22f40_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['staff', 'type', 'related_date'], name='staff_notif_staff_i_bfc413_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-created_at'], name='staff_notif_is_read_65dcb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('staff', 'type', 'related_date'), name='uniq_notification_per_staff_type_date'),
        ),
        migrations.AddIndex(
            model_name='staffpromotion',
            index=models.Index(fields=['staff', '-promotion_date'], name='staff_staff_staff_i_9e63c3_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftransfer',
            index=models.Index(fields=['staff', '-transfer_date'], name='staff_staff_staff_i_641414_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftransfer',
            index=models.Index(fields=['to_location'], name='staff_staff_to_loca_767d73_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftransfer',
            index=models.Index(fields=['from_location'], name='staff_staff_from_lo_fc3089_idx'),
        ),
    ]
