# Generated by Django 5.1.15 on 2026-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nhis_nhf_signature_year_of_call_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Pending', 'Pending'), ('Secondment', 'Secondment'), ('Suspension', 'Suspension'), ('Retirement', 'Retirement'), ('Resignation', 'Resignation'), ('Deceased', 'Deceased'), ('Archive', 'Archive')], default='Active', help_text='Current employment status', max_length=50),
        ),
    ]
