# Generated by Django 5.1.15 on 2026-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_additional_next_of_kin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='passport_photo',
            field=models.ImageField(blank=True, help_text='Passport-size photograph (optional)', null=True, upload_to='passport_photos/%Y/%m/'),
        ),
    ]
