# Generated by Django 5.1.15 on 2026-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='secret_file_number',
            field=models.CharField(blank=True, help_text='Confidential personnel file reference (e.g. CCA/SF/2026/0001).', max_length=50, null=True),
        ),
    ]
