# Generated by Django 5.1.15 on 2026-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_secret_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_increment_date',
            field=models.DateField(blank=True, help_text="Date the staff's step was last incremented (auto-set).", null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_increment_date',
            field=models.DateField(blank=True, help_text='Next scheduled step-increment date (1 Jan or 1 Jul, auto-set).', null=True),
        ),
    ]
