# Generated by Django 5.1.15 on 2026-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, help_text="Official email address (optional). Blank stored as NULL so multiple staff without an email don't clash on the unique index.", max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number (optional)', max_length=20, null=True),
        ),
    ]
