# Generated by Django 5.1.15 on 2026-07-06 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_sync_fields'),
        ('staff', '0009_alter_staff_email_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='agency',
            field=models.CharField(blank=True, help_text='Parent agency / establishment', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='cadre',
            field=models.CharField(blank=True, help_text='Cadre / job stream (e.g. Legal, Administration)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Educational qualifications (one per line; captured from bulk import)', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit within the department', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth (optional — bulk imports may omit it)', null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Current department (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Current designation/rank (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.designation'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_appointment_date',
            field=models.DateField(blank=True, help_text='Date of first appointment to the organization (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender (optional)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name/Surname', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, default='Nigerian', help_text='Nationality', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='state_of_origin',
            field=models.CharField(blank=True, help_text='State of origin in Nigeria', max_length=100),
        ),
    ]
