# Generated by Django 5.1.15 on 2026-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staff_agency_staff_cadre_staff_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='residential_address',
            field=models.TextField(blank=True, help_text='Current residential address (optional)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='residential_city',
            field=models.CharField(blank=True, help_text='City of residence (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='residential_state',
            field=models.CharField(blank=True, help_text='State of residence (optional)', max_length=100),
        ),
    ]
