# Generated by Django 5.1.15 on 2026-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_staff_residential_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='file_number',
            field=models.CharField(blank=True, help_text="Personnel file number (open registry, e.g. from the nominal roll's FileNo).", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='present_appointment_date',
            field=models.DateField(blank=True, help_text='Date of present appointment / posting (DOPE on the nominal roll).', null=True),
        ),
    ]
