# Generated by Django 5.1.15 on 2026-07-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staff_file_number_staff_present_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_confirmed',
            field=models.DateField(blank=True, help_text='Date the appointment was confirmed.', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(blank=True, help_text='Duty post / location as recorded on the nominal roll (free text).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pay_status',
            field=models.CharField(blank=True, help_text='Payroll status from the nominal roll (e.g. Active).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pension_administrator',
            field=models.CharField(blank=True, help_text='Pension Fund Administrator (PFA).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent / home-town address (distinct from residential address).', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='rsa_pin',
            field=models.CharField(blank=True, help_text='Retirement Savings Account (RSA) PIN / Pension number.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='sort_code',
            field=models.CharField(blank=True, help_text='Bank branch sort code.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, help_text='Courtesy title (Mr, Mrs, Dr, Barr., etc.)', max_length=20, null=True),
        ),
    ]
