# Generated by Django 5.1.15 on 2026-07-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staff_date_confirmed_staff_location_staff_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Pending', 'Pending'), ('STOP PAY', 'STOP PAY'), ('Secondment', 'Secondment'), ('Suspension', 'Suspension'), ('Retirement', 'Retirement'), ('Resignation', 'Resignation'), ('Deceased', 'Deceased'), ('Archive', 'Archive')], default='Active', help_text='Current employment status', max_length=50),
        ),
    ]
