# Generated by Django 5.1.15 on 2026-07-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_staff_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='organizational_role',
            field=models.CharField(blank=True, choices=[('Chief Registrar', 'Chief Registrar'), ('Director', 'Director'), ('Deputy Director', 'Deputy Director'), ('Head of Department', 'Head of Department'), ('Head of Unit', 'Head of Unit'), ('Judge', 'Judge')], help_text="Hierarchy/role label; 'Judge' also lists the officer in the Judges section (judges still appear in the main staff roll).", max_length=40, null=True),
        ),
    ]
