# Generated by Django 5.1.15 on 2026-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staff_organizational_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='judge_order',
            field=models.PositiveIntegerField(blank=True, help_text='Manual display order for the Judges list (lower = higher up). Set by admins on the Judges page.', null=True),
        ),
    ]
