#!/usr/bin/env bash
# 02 — PostgreSQL: create role + DB with least privilege, install daily backup.
#
# Re-running this script is safe; it skips creation when objects exist and
# only regenerates the password if you pass --rotate-password.

# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"
require_root

ROTATE=0
[[ "${1:-}" == "--rotate-password" ]] && ROTATE=1

require_cmd sudo
require_cmd openssl

# --- Role ---------------------------------------------------------------------
ROLE_EXISTS=$(sudo -u postgres psql -tAc \
    "SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}'")

if [[ "${ROLE_EXISTS}" == "1" && "${ROTATE}" -eq 0 ]]; then
    warn "Role ${DB_USER} already exists. Pass --rotate-password to reset its password."
    NEW_PASSWORD=""
else
    NEW_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | cut -c1-32)
    if [[ "${ROLE_EXISTS}" == "1" ]]; then
        log "Rotating password for ${DB_USER}"
        sudo -u postgres psql -v ON_ERROR_STOP=1 -c \
            "ALTER ROLE \"${DB_USER}\" WITH PASSWORD '${NEW_PASSWORD}';"
    else
        log "Creating role ${DB_USER}"
        sudo -u postgres psql -v ON_ERROR_STOP=1 -c \
            "CREATE ROLE \"${DB_USER}\" WITH LOGIN PASSWORD '${NEW_PASSWORD}' \
             NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;"
    fi
fi

# --- Database -----------------------------------------------------------------
DB_EXISTS=$(sudo -u postgres psql -tAc \
    "SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}'")

if [[ "${DB_EXISTS}" != "1" ]]; then
    log "Creating database ${DB_NAME} owned by ${DB_USER}"
    sudo -u postgres createdb -O "${DB_USER}" -E UTF8 "${DB_NAME}"
fi

# --- Least-privilege grants ---------------------------------------------------
# The role owns the DB, so it can manage its own schema during `migrate`.
# We still revoke privileges on the postgres maintenance DB and ensure no
# implicit access to other DBs.
log "Tightening role privileges"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
REVOKE ALL ON DATABASE postgres FROM "${DB_USER}";
REVOKE ALL ON DATABASE template1 FROM "${DB_USER}";
GRANT CONNECT, TEMP ON DATABASE "${DB_NAME}" TO "${DB_USER}";
SQL

sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" <<SQL
GRANT USAGE, CREATE ON SCHEMA public TO "${DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${DB_USER}";
SQL

# --- Backup script + cron -----------------------------------------------------
log "Installing /usr/local/bin/biodata-backup.sh"
install -m 0750 -o root -g root /dev/null /usr/local/bin/biodata-backup.sh
cat > /usr/local/bin/biodata-backup.sh <<EOF
#!/usr/bin/env bash
# Daily pg_dump → gzip, with rotation. Generated by 02_postgres_setup.sh.
set -euo pipefail

BACKUP_DIR="${BACKUP_DIR}"
RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
DB_NAME="${DB_NAME}"

install -d -o postgres -g postgres -m 0750 "\$BACKUP_DIR"
ts=\$(date +%Y%m%d_%H%M%S)
out="\$BACKUP_DIR/\${DB_NAME}_\${ts}.sql.gz"

sudo -u postgres pg_dump --format=plain --no-owner --no-acl "\$DB_NAME" \\
    | gzip -9 > "\$out"

chmod 0640 "\$out"
chown postgres:postgres "\$out"

# Rotate
find "\$BACKUP_DIR" -name "\${DB_NAME}_*.sql.gz" -mtime +\$RETENTION_DAYS -delete

# Quick integrity check — gzip -t exits non-zero on corruption.
gzip -t "\$out"

logger -t biodata-backup "wrote \$out"
EOF
chmod 0750 /usr/local/bin/biodata-backup.sh

install -d -o postgres -g postgres -m 0750 "${BACKUP_DIR}"

# Cron entry (idempotent — overwrite our managed file)
cat > /etc/cron.d/biodata-backup <<EOF
# Daily PostgreSQL dump of ${DB_NAME}. Managed by deploy/02_postgres_setup.sh.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
${BACKUP_CRON_TIME} root /usr/local/bin/biodata-backup.sh
EOF
chmod 0644 /etc/cron.d/biodata-backup

systemctl reload cron || systemctl restart cron

# --- Final output -------------------------------------------------------------
if [[ -n "${NEW_PASSWORD}" ]]; then
    echo
    echo "========================================================================"
    echo " Database password for ${DB_USER}@${DB_NAME}:"
    echo
    echo "   ${NEW_PASSWORD}"
    echo
    echo " Copy this into ${PROJECT_DIR}/.env as DB_PASSWORD now."
    echo " It will not be shown again."
    echo "========================================================================"
fi
