# Generated by Django 5.1.15 on 2026-05-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=365, help_text='Number of days to retain audit logs before archiving')),
                ('archive_old_logs', models.BooleanField(default=True, help_text='Whether to archive old logs instead of deleting')),
                ('log_all_views', models.BooleanField(default=False, help_text='Whether to log every view/read action')),
                ('log_failed_logins', models.BooleanField(default=True, help_text='Whether to log failed login attempts')),
                ('notify_on_critical_changes', models.BooleanField(default=True, help_text='Whether to send notifications on critical record changes')),
                ('critical_models', models.JSONField(default=list, help_text='List of model names to consider as critical')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Settings',
                'verbose_name_plural': 'Audit Settings',
                'db_table': 'audit_auditsettings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Username of the user who performed the action', max_length=200)),
                ('user_email', models.EmailField(blank=True, help_text='Email of the user who performed the action', max_length=254, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('SEARCH', 'Search'), ('DOWNLOAD', 'Download'), ('EXPORT', 'Export'), ('BULK_IMPORT', 'Bulk Import'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('OTHER', 'Other')], help_text='Type of action performed', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model/table affected', max_length=100)),
                ('record_id', models.CharField(help_text='ID of the record affected', max_length=200)),
                ('record_identifier', models.CharField(blank=True, help_text='Human-readable identifier of the record (e.g., staff name)', max_length=500, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values of changed fields (JSON)', null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values of changed fields (JSON)', null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, help_text='List of fields that were changed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the browser/client', null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, help_text='Request URL path', max_length=500, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the action', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], default='SUCCESS', help_text='Status of the action', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_audit_user_b4fdeb_idx'), models.Index(fields=['model_name', 'record_id'], name='audit_audit_model_n_95032e_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_audit_ip_addr_ed092b_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_log_id', models.BigIntegerField(help_text='Original audit log ID')),
                ('user', models.CharField(max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=200)),
                ('record_identifier', models.CharField(blank=True, max_length=500, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log Archive',
                'verbose_name_plural': 'Audit Log Archives',
                'db_table': 'audit_auditlogarchive',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='audit_audit_model_n_2ae7b4_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_b8a872_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tried', models.CharField(help_text='The identifier (username or email) the user typed.', max_length=200)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Resolved user (only set on success or known account).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_loginattempt',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username_tried', '-timestamp'], name='audit_login_usernam_221511_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_login_ip_addr_e0f32f_idx'), models.Index(fields=['success', '-timestamp'], name='audit_login_success_7925e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EXCESSIVE_VIEWS', 'Excessive record views'), ('NEW_IP_LOGIN', 'Login from a new IP'), ('FAILED_LOGINS', 'Repeated failed login attempts'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('username', models.CharField(blank=True, default='', help_text='Username at time of event (kept even if user is later deleted).', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=200)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_suspiciousactivity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='audit_suspi_kind_a8effc_idx'), models.Index(fields=['is_acknowledged', '-created_at'], name='audit_suspi_is_ackn_0f23fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserKnownIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_userknownip',
                'indexes': [models.Index(fields=['user', '-last_seen'], name='audit_userk_user_id_a5a837_idx')],
                'unique_together': {('user', 'ip_address')},
            },
        ),
    ]
